[versions]
netty = "4.1.115.Final"
slf4j = "2.0.16"
protobuf = "3.25.5"
protobufPlugin = "0.9.4"
springBoot = "3.4.1"
junit = "5.11.3"
nacos = "2.4.3"
grpc = "1.69.0"
micrometer = "1.14.2"
opentelemetry = "1.45.0"
aeron = "1.49.3"
lettuce = "6.5.2.RELEASE"

[libraries]
netty-bom = { module = "io.netty:netty-bom", version.ref = "netty" }
netty-buffer = { module = "io.netty:netty-buffer" }
netty-common = { module = "io.netty:netty-common" }
netty-transport = { module = "io.netty:netty-transport" }
netty-handler = { module = "io.netty:netty-handler" }
netty-codec = { module = "io.netty:netty-codec" }
netty-codec-http = { module = "io.netty:netty-codec-http" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobuf-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf" }

spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "springBoot" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "springBoot" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "springBoot" }

micrometer-core = { module = "io.micrometer:micrometer-core", version.ref = "micrometer" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer" }

opentelemetry-api = { module = "io.opentelemetry:opentelemetry-api", version.ref = "opentelemetry" }
opentelemetry-context = { module = "io.opentelemetry:opentelemetry-context", version.ref = "opentelemetry" }

nacos-client = { module = "com.alibaba.nacos:nacos-client", version.ref = "nacos" }

grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }

lettuce-core = { module = "io.lettuce:lettuce-core", version.ref = "lettuce" }
aeron-all = { module = "io.aeron:aeron-all", version.ref = "aeron" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
